### ISSUE TITLE
Is it possible to support Office 2016?

### ISSUE THREAD

**Issue by tedaz** [myanaloglife/py-kms#3]
Is it possible to support Office 2016?

**Comment by johnny-jiang** [comment]
by add some UUIDs, it support.
`
                 uuid.UUID("d450596f-894d-49e0-966a-fd39ed4c4c64"): "Office Professional Plus 2016",
                 uuid.UUID("4f414197-0fc2-4c01-b68a-86cbb9ac254c"): "Office Project Pro 2016",  
                 uuid.UUID("6bf301c1-b94a-43e9-ba31-d494598c47fb"): "Office Visio Pro 2016", 
                 uuid.UUID("041a06cb-c5b8-4772-809f-416d03d16654"): "Office Publisher 2016",
                 uuid.UUID("67c0fc0c-deba-401b-bf8b-9c8ad8395804"): "Office Access 2016",  
                 uuid.UUID("83e04ee1-fa8d-436d-8994-d31a862cab77"): "Office Skype for Business 2016", 
                 uuid.UUID("9caabccb-61b1-4b4b-8bec-d10a3c3ac2ce"): "Office Mondo 2016",  
                 uuid.UUID("aa2a7821-1827-4c2c-8f1d-4513a34dda97"): "Office Visio Standard 2016",
                 uuid.UUID("bb11badf-d8aa-470e-9311-20eaf80fe5cc"): "Office Word 2016",   
                 uuid.UUID("c3e65d36-141f-4d2f-a303-a842ee756a29"): "Office Excel 2016",
                 uuid.UUID("d70b1bba-b893-4544-96e2-b7a318091c33"): "Office Powerpoint 2016", 
                 uuid.UUID("d8cace59-33d2-4ac7-9b1b-9b72339c51c8"): "Office OneNote 2016",  
                 uuid.UUID("da7ddabc-3fbe-4447-9e01-6ab7440b4cd4"): "Office Project Standard 2016", 
                 uuid.UUID("dedfa23d-6ed1-45a6-85dc-63cae0546de6"): "Office Standard 2016", 
                 uuid.UUID("e914ea6e-a5fa-4439-a394-a9bb3293ca09"): "Office Mondo R 2016", 
                 uuid.UUID("ec9d9265-9d1e-4ed0-838a-cdc20f2551a1"): "Office Outlook 2016",`

add them in `skuIds` of kmsBase.py, then it will support office 2016.
